-- ============================================================================
-- Migration: Initial Schema for GeeCON Q&A System
-- Created: 2026-01-26 12:00:00 UTC
-- Description: Creates the core schema for Q&A sessions including:
--              - sessions table for conference talks
--              - questions table for audience questions
--              - invites table for moderator onboarding
--              - RLS policies for anon and authenticated users
--              - Performance indexes
-- ============================================================================

-- ============================================================================
-- 1. ENUM TYPES
-- ============================================================================

-- Create enum type for invite status tracking
-- Used to manage lifecycle of moderator invitations
create type invite_status as enum ('active', 'used', 'expired');

-- ============================================================================
-- 2. TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 2.1 sessions table
-- ----------------------------------------------------------------------------
-- Stores Q&A sessions for individual conference talks
-- Each session has a unique URL slug for public access
create table sessions (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    speaker text not null,
    description text,
    session_date timestamptz,
    unique_url_slug text unique not null,
    created_at timestamptz not null default now()
);

-- Add table comment for documentation
comment on table sessions is 'Q&A sessions for conference talks';
comment on column sessions.unique_url_slug is 'Random unique identifier for session URL - must be generated by application';
comment on column sessions.session_date is 'Scheduled date and time of the conference talk';

-- ----------------------------------------------------------------------------
-- 2.2 questions table
-- ----------------------------------------------------------------------------
-- Stores questions submitted by audience members during Q&A sessions
-- Includes upvote counter and answered status for moderation
create table questions (
    id uuid primary key default gen_random_uuid(),
    session_id uuid not null,
    content text not null check (char_length(content) >= 5 and char_length(content) <= 500),
    author_name text not null default 'Anonymous',
    is_answered boolean not null default false,
    upvote_count integer not null default 0 check (upvote_count >= 0),
    created_at timestamptz not null default now(),
    constraint questions_session_id_fkey 
        foreign key (session_id) 
        references sessions(id) 
        on delete cascade
);

-- Add table comments for documentation
comment on table questions is 'Questions submitted by conference attendees';
comment on column questions.content is 'Question text - must be between 5 and 500 characters';
comment on column questions.upvote_count is 'Number of upvotes - denormalized for MVP performance';
comment on column questions.is_answered is 'Flag indicating if moderator has addressed this question';
comment on constraint questions_session_id_fkey on questions is 'Cascade delete: removing session deletes all its questions';

-- ----------------------------------------------------------------------------
-- 2.3 invites table
-- ----------------------------------------------------------------------------
-- Stores one-time invitation tokens for new moderator onboarding
-- Invites expire after 72 hours by default
create table invites (
    id uuid primary key default gen_random_uuid(),
    token text unique not null,
    created_by_moderator_id uuid references auth.users(id),
    expires_at timestamptz not null default (now() + interval '72 hours'),
    status invite_status not null default 'active',
    created_at timestamptz not null default now()
);

-- Add table comments for documentation
comment on table invites is 'One-time invitation tokens for moderator onboarding';
comment on column invites.token is 'Unique invitation token - should be cryptographically secure';
comment on column invites.expires_at is 'Invitation expiration timestamp - defaults to 72 hours from creation';
comment on column invites.status is 'Invite lifecycle status: active, used, or expired';

-- ============================================================================
-- 3. ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on all tables
-- This ensures all data access is controlled by explicit policies
alter table sessions enable row level security;
alter table questions enable row level security;
alter table invites enable row level security;

-- ----------------------------------------------------------------------------
-- 3.1 RLS Policies for sessions table
-- ----------------------------------------------------------------------------

-- Allow anonymous users (conference attendees) to view all sessions
-- Purpose: Public can browse available Q&A sessions
create policy "anon_select_sessions"
    on sessions
    for select
    to anon
    using (true);

-- Allow authenticated moderators to view all sessions
-- Purpose: Moderators need full visibility of all sessions
create policy "authenticated_select_sessions"
    on sessions
    for select
    to authenticated
    using (true);

-- Allow authenticated moderators to create new sessions
-- Purpose: Moderators can set up Q&A sessions for talks
create policy "authenticated_insert_sessions"
    on sessions
    for insert
    to authenticated
    with check (true);

-- Allow authenticated moderators to update any session
-- Purpose: Moderators can edit session details (name, speaker, date, etc.)
create policy "authenticated_update_sessions"
    on sessions
    for update
    to authenticated
    using (true)
    with check (true);

-- Allow authenticated moderators to delete any session
-- Purpose: Moderators can remove sessions (cascades to questions)
-- WARNING: This is a destructive operation that deletes all associated questions
create policy "authenticated_delete_sessions"
    on sessions
    for delete
    to authenticated
    using (true);

-- ----------------------------------------------------------------------------
-- 3.2 RLS Policies for questions table
-- ----------------------------------------------------------------------------

-- Allow anonymous users to view all questions
-- Purpose: Conference attendees can see questions submitted by others
create policy "anon_select_questions"
    on questions
    for select
    to anon
    using (true);

-- Allow anonymous users to submit questions
-- Purpose: Conference attendees can ask questions during Q&A
create policy "anon_insert_questions"
    on questions
    for insert
    to anon
    with check (true);

-- Allow authenticated moderators to view all questions
-- Purpose: Moderators need full visibility to manage Q&A
create policy "authenticated_select_questions"
    on questions
    for select
    to authenticated
    using (true);

-- Allow authenticated moderators to create questions
-- Purpose: Moderators can add questions on behalf of attendees
create policy "authenticated_insert_questions"
    on questions
    for insert
    to authenticated
    with check (true);

-- Allow authenticated moderators to update any question
-- Purpose: Moderators can mark questions as answered, update content, or adjust upvote count
create policy "authenticated_update_questions"
    on questions
    for update
    to authenticated
    using (true)
    with check (true);

-- Allow authenticated moderators to delete any question
-- Purpose: Moderators can remove inappropriate or duplicate questions
-- WARNING: This is a destructive operation - physical delete, not soft delete
create policy "authenticated_delete_questions"
    on questions
    for delete
    to authenticated
    using (true);

-- ----------------------------------------------------------------------------
-- 3.3 RLS Policies for invites table
-- ----------------------------------------------------------------------------

-- No access for anonymous users to invites table
-- This is enforced by RLS being enabled with no anon policies

-- Allow authenticated moderators to view all invites
-- Purpose: Moderators can see invitation status and manage access
create policy "authenticated_select_invites"
    on invites
    for select
    to authenticated
    using (true);

-- Allow authenticated moderators to create new invites
-- Purpose: Moderators can generate invitation tokens for new moderators
create policy "authenticated_insert_invites"
    on invites
    for insert
    to authenticated
    with check (true);

-- Allow authenticated moderators to update invite status
-- Purpose: Moderators can mark invites as used or expired
create policy "authenticated_update_invites"
    on invites
    for update
    to authenticated
    using (true)
    with check (true);

-- Allow authenticated moderators to delete invites
-- Purpose: Moderators can revoke unused invitations
create policy "authenticated_delete_invites"
    on invites
    for delete
    to authenticated
    using (true);

-- ============================================================================
-- 4. PERFORMANCE INDEXES
-- ============================================================================

-- Index for efficient question sorting by popularity and recency
-- Used when displaying questions ordered by upvotes (descending) then creation time (ascending)
create index idx_questions_sorting 
on questions (upvote_count desc, created_at asc);

-- Index for filtering questions by session
-- Optimizes queries that fetch all questions for a specific Q&A session
create index idx_questions_session_id 
on questions (session_id);

-- Index for fast session lookup by URL slug
-- Optimizes public access to sessions via unique URL
-- Note: UNIQUE constraint already creates an index, but explicit index improves clarity
create index idx_sessions_unique_url_slug 
on sessions (unique_url_slug);

-- Composite index for invite queries
-- Optimizes queries checking for active, non-expired invitations
create index idx_invites_status_expires 
on invites (status, expires_at);

-- ============================================================================
-- 5. GRANTS (Additional layer beyond RLS for defense in depth)
-- ============================================================================

-- Grant basic select permission to anonymous users on sessions
-- RLS policies further restrict actual row visibility
grant select on sessions to anon;

-- Grant select and insert permissions to anonymous users on questions
-- RLS policies ensure appropriate access control
grant select, insert on questions to anon;

-- No grants for anonymous users on invites table
-- Ensures invitations are only accessible to authenticated moderators
revoke all on invites from anon;

-- Grant full permissions to authenticated users on all tables
-- RLS policies provide granular control within these permissions
grant select, insert, update, delete on sessions to authenticated;
grant select, insert, update, delete on questions to authenticated;
grant select, insert, update, delete on invites to authenticated;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Note: First administrator must be manually added to auth.users table
-- Note: Application is responsible for generating cryptographically secure
--       values for sessions.unique_url_slug and invites.token
-- ============================================================================
